WorkoutandDiet:
  path: /WorkoutandDiet
  controller: App\Controller\DefaultController::WorkoutandDiet

WorkoutChoice:
  path: /WorkoutChoice
  controller: App\Controller\DefaultController::WorkoutList

DietChoice:
  path: /DietChoice
  controller: App\Controller\DefaultController::DietList



searchWorkout:
  path: /searchWorkout
  controller: App\Controller\WorkoutController::searchWorkout

searchDiet:
  path: /searchDiet
  controller: App\Controller\DietController::searchDiet

searchIngredient:
  path: /searchIngredient
  controller: App\Controller\IngredientController::searchIngredient



DietpdfList:
  path: /DietpdfList
  controller: App\Controller\DietController::listPDF



WorkoutStats:
  path: /WorkoutStats
  controller: App\Controller\WorkoutController::WorkoutStats

IngredientStats:
  path: /IngredientStats
  controller: App\Controller\IngredientController::IngredientStats

DietStats:
  path: /DietStats
  controller: App\Controller\DietController::DietStats





Diet1600:
  path: /Diet1600
  controller: App\Controller\DefaultController::D1600list

Diet1800:
  path: /Diet1800
  controller: App\Controller\DefaultController::D1800list

Diet2000:
  path: /Diet2000
  controller: App\Controller\DefaultController::D2000list

Diet2200:
  path: /Diet2200
  controller: App\Controller\DefaultController::D2200list

Diet2400:
  path: /Diet2400
  controller: App\Controller\DefaultController::D2400list

Diet2600:
  path: /Diet2600
  controller: App\Controller\DefaultController::D2600list



WorkoutArms:
  path: /WorkoutArms
  controller: App\Controller\DefaultController::ArmsWlist

WorkoutShoulders:
  path: /WorkoutShoulders
  controller: App\Controller\DefaultController::ShouldersWlist

WorkoutAbs:
  path: /WorkoutAbs
  controller: App\Controller\DefaultController::AbsWlist

WorkoutChest:
  path: /WorkoutChest
  controller: App\Controller\DefaultController::ChestWlist

WorkoutBack:
  path: /WorkoutBack
  controller: App\Controller\DefaultController::BackWlist

WorkoutLegs:
  path: /WorkoutLegs
  controller: App\Controller\DefaultController::LegsWlist

WorkoutGlutes:
  path: /WorkoutGlutes
  controller: App\Controller\DefaultController::GlutesWlist



testing:
  path: /test
  controller: App\Controller\DefaultController::testfunction