WorkoutandDiet:
  path: /WorkoutandDiet
  controller: App\Controller\DefController::WorkoutandDiet

WorkoutChoice:
  path: /WorkoutChoice
  controller: App\Controller\DefController::WorkoutList

DietChoice:
  path: /DietChoice
  controller: App\Controller\DefController::DietList



searchWorkout:
  path: /searchWorkout
  controller: App\Controller\WorkoutController::searchWorkout

searchDiet:
  path: /searchDiet
  controller: App\Controller\DietController::searchDiet

searchIngredient:
  path: /searchIngredient
  controller: App\Controller\IngredientController::searchIngredient




Diet1600:
  path: /Diet1600
  controller: App\Controller\DefController::D1600list

Diet1800:
  path: /Diet1800
  controller: App\Controller\DefController::D1800list

Diet2000:
  path: /Diet2000
  controller: App\Controller\DefController::D2000list

Diet2200:
  path: /Diet2200
  controller: App\Controller\DefController::D2200list

Diet2400:
  path: /Diet2400
  controller: App\Controller\DefController::D2400list

Diet2600:
  path: /Diet2600
  controller: App\Controller\DefController::D2600list



WorkoutArms:
  path: /WorkoutArms
  controller: App\Controller\DefController::ArmsWlist

WorkoutShoulders:
  path: /WorkoutShoulders
  controller: App\Controller\DefController::ShouldersWlist

WorkoutAbs:
  path: /WorkoutAbs
  controller: App\Controller\DefController::AbsWlist

WorkoutChest:
  path: /WorkoutChest
  controller: App\Controller\DefController::ChestWlist

WorkoutBack:
  path: /WorkoutBack
  controller: App\Controller\DefController::BackWlist

WorkoutLegs:
  path: /WorkoutLegs
  controller: App\Controller\DefController::LegsWlist

WorkoutGlutes:
  path: /WorkoutGlutes
  controller: App\Controller\DefController::GlutesWlist




DietpdfList:
  path: /DietpdfList
  controller: App\Controller\DietController::listPDF

WorkoutSMS:
  path: /WorkoutSMS
  controller: App\Controller\DefController::WorkoutSMS




WorkoutStats:
  path: /WorkoutStats
  controller: App\Controller\WorkoutController::WorkoutStats

IngredientStats:
  path: /IngredientStats
  controller: App\Controller\IngredientController::IngredientStats

DietStats:
  path: /DietStats
  controller: App\Controller\DietController::DietStats



ScreenShotWorkout:
  path: /ScreenShotWorkout
  controller: App\Controller\DefController::ScreenShotWorkout

ScreenShotDiet:
  path: /ScreenShotDiet
  controller: App\Controller\DefController::ScreenShotDiet

ScreenShotIngredient:
  path: /ScreenShotIngredient
  controller: App\Controller\DefController::ScreenShotIngredient